# Generated by Django 3.2.16 on 2022-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0076_level_locked_for_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={"ordering": ["block_type", "pk"]},
        ),
        migrations.AddField(
            model_name="block",
            name="block_type",
            field=models.IntegerField(
                choices=[
                    (0, "Start"),
                    (1, "Action"),
                    (2, "Condition"),
                    (3, "Proedure"),
                    (4, "ControlFlow"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
